### ISSUE TITLE
Error connecting to Facebook API via source feed error

### ISSUE THREAD

**Issue by akabucko** [verbb/social-feeds#7] opened 2023-11-22 10:56 UTC
### Describe the bug

After setting up the social feeds app and it has been working fine, I'm now running into an error connecting to the Facebook API via the source feed "Sorry, something went wrong. We're working on getting this fixed as soon as we can." on Facebook side. Nothing is coming up in the logs, any help on this would be appreciated.

### Steps to reproduce

1. Social feeds: Add new source 
2. Fill out the Source and Provider information (see image attached)
3. Save the source
4. Connect to Facebook and log in
5. "Sorry, something went wrong. We're working on getting this fixed as soon as we can. Go back" error. (see image attached)
<img width="1499" alt="social-feed-setup" src="https://github.com/verbb/social-feeds/assets/26873231/a6e53da7-d8da-4d47-80f0-ed9fa251c6f9">
<img width="1504" alt="Facebook error" src="https://github.com/verbb/social-feeds/assets/26873231/f786434c-8c74-4c28-8782-13a51d251295">

### Craft CMS version

4.56

### Plugin version

1.0.2

**Comment by engram-design** [comment] 2023-11-22 11:37
From experience, this error from Facebook seems to be when there's invalid (or missing) scopes for the connection, or something amiss about the Facebook app. First thing to check is the Facebook app, and if there's any data-integrity checks you need to do (you need to do these periodically).

One thing to check with your app - are you using `Facebook login for Business` or `Facebook Login`?

You can change the `scopes` via the [config](https://verbb.io/craft-plugins/social-feeds/docs/get-started/configuration) and it might pay to test commenting some of the [default ones](https://github.com/verbb/social-feeds/blob/adae4556cab6b73ea8c91a5baf234cfb622059cd/src/sources/Facebook.php#L77-L86) as a trial-and-error.

What Facebook API version does your app use?

**Comment by jamesmacwhite** [comment] 2024-02-07 11:46
Hi @engram-design. I'm getting the same as well but could totally be a setup issue on the Facebook App side or something I'm missing. I noticed @akabucko didn't reply, but happy to dig into it further to confirm.

I don't know if the Graph API version could do with a bump as well given it is Version 15 in the plugin, but I believe v19 is the latest? I did locally test changing this, but it doesn't change the error, so I'm assuming it's a scope/OAuth issue still somewhere.

**Comment by jamesmacwhite** [comment] 2024-02-07 12:47
From some initial testing, it could be the issue between Facebook Login and Facebook Business Login. The app is linked to a Facebook Business account.

**Comment by engram-design** [comment] 2024-02-07 13:13
I don't think the API version should do this, but I can confirm there is a difference between Facebook Login and Facebook Business Login that is most likely causing this. I can't quite recall which is the "correct" one, as one is the newest. I believe you need different scopes based on which product you use. It's the reason for the note is the [docs](https://verbb.io/craft-plugins/social-feeds/docs/providers/facebook):

> Ensure that you pick Facebook Login and not Facebook Login for Business, which are different products. If you must use Facebook Login for Business, you'll need to provide additional scopes.

Just about to head off for the day, but can circle back to this.

**Comment by jamesmacwhite** [comment] 2024-02-07 21:26
No problem!

I've confirmed it's not anything to do with the API version, but just a note that the Graph API version set in the plugin is 15 and currently the latest version is 19.

I have selected Facebook Login as this appears to be a selectable option when adding a product to an app, I did not see an option for Facebook Business Login referenced. However, the Facebook Page in question is linked to a Facebook Business account, so I'm wondering if we cannot use the standard Facebook login in this case, and must go through Business Login. I need to check if this an option as I couldn't see it when following the setup guide.

I've noted that removing the defaultScopes, allows the OAuth to work, but missing the required page permissions needed for the functionality, but public_profile and email scopes work, so we now know it's the specific page related scopes at least.

Edit: I can see the category of Other > Business, provides the Facebook Business Login option, but when setting up an app with the same information and extra auth scopes, it throws the same error. However again removing any of the page OAuth scopes, it will complete OK.

**Comment by engram-design** [comment] 2024-02-07 22:35
Right, so that's interesting. Those scopes should be valid once the login has been approved. How about switching to the Facebook Business Login app, and adding that scope as well?

I'll investigate further on my end. Facebook are seemingly always changing something!!

**Comment by jamesmacwhite** [comment] 2024-02-07 22:44
I tested a Facebook Business login app and got the same error, as soon as the default page scopes are requested, OAuth is rejected with the same generic error (would it hurt Facebook to provide debug info?!), however removing all the page scopes, allows the login to work, but of course the page selector is blank, given it's not get any visibility of pages. Adding `business_management` scope also works, it appears specific to any page related OAuth scopes, is breaking things.

The Facebook account used has admin on the Facebook page, however the permissions are handled through Meta Business Manager, so this may be where things are falling down potentially.

Hope that helps at least initially. Facebook don't make it easy and have possibly changed some of the app setup screens. I note that in several places, it is stated that they've "changed the options available" based on the type of app you select on the initial creation stage. This explains why "Facebook Business login" is no where to be seen unless you choose Other > Business for the app type at the very beginning!

**Comment by engram-design** [comment] 2024-02-07 23:31
Okay, so something has clearly changed with Facebook on this, as I'm getting a few people reporting the same issue.

I'm going through the process again, and just to be clear, did you pick anything in the **Business Portfolio** field when setting up your app? 
<img width="812" alt="image" src="https://github.com/verbb/social-feeds/assets/1221575/9527479e-5df0-4452-b319-159081a31567">

**Comment by engram-design** [comment] 2024-02-08 00:23
Actually, just reviewing my docs that say to put the app into **Live** mode, and that requires a Facebook App Review.

> [App Review ](https://developers.facebook.com/docs/app-review) is required for all permissions except for `email` and `public_profile` if your app needs access to data that you do not own or manage.

So that would explain part of it, but at some point you could access this data at some point without an app review... But now I'm also having issues connecting with my instructions, so you're not the only one.

Still investigating this one.

**Comment by jamesmacwhite** [comment] 2024-02-08 06:24
No worries. I do think Facebook have changed things more recently since you originally wrote your docs and the original author when they made this issue didn't responsd, so you had no information or context. Unhelpfully as well. the generic error page given by Facebook also does not provide anything as to what happened either, so Meta aren't helping either!

When testing the Facebook Business Login route, I did select our Business Manager account, as our Facebook Page is managed through Meta Business Suite.

In terms of the Development vs Live scenario, I don't know if it's absolutely required in all cases. There's another Craft CMS plugin which uses the Instagram Basic Display API, which doesn't need to be made "live", you do however have to assign specific roles however. https://github.com/scaramangagency/craftagram.

Let me know if you need to me to any further testing or try anything. I've got a development environment with the latest Craft CMS 4 branch configured as a local plugin, so I can modify the OAuth scopes and such directly for debug.

**Comment by engram-design** [comment] 2024-02-08 11:21
Yeah, I believe the general rule is the "live" is for accessing other users' data, while "dev" mode is fine for accessing yours. And that's extended to what you have access to. If you have editor/admin access to another users page, then that's covered in "dev" mode. Which is similar for the Craftagram plugin which requires you to grant access to the Instagram user (which doesn't have to be on the same account as the Facebook account you login and authenticate with Craft).

Anyway! After a bit of trial and error and different combinations, I've found one that works. It requires creating a Business app, then switching from **Facebook Login for Business** to plain **Facebook Login**. It seems you get plenty more permissions for a Business app, with plain Facebook Login. Go figure.

One change I need to make is that the `groups_access_member_info` no longer seems to be included, so you'll need to manually comment this scope out.

You can also keep the Facebook app in Dev mode.

If you want to follow my updated instructions before I make changes on my end?

### Step 2: Register a Facebook App
1. Go to the <a href="https://developers.facebook.com/apps/" target="_blank">Meta for Developers</a> page.
1. Click the **Create App** button.
1. Select **Other** and click the **Next** button.
1. Select **Business** and click the **Next** button.
1. Fill in the **App Name** and **App Contact Email**. The **Business Portfolio** is optional.

### Step 3: Setup Facebook Login
1. Once created, in the left-hand sidebar, click the **Add Product** button.
1. Under **Facebook Login for Business** click the **Set Up** button.
1. A warning banner will appear **Are you looking for other options?** to switch to Facebook Login. Click the **Switch to Facebook Login** link.
1. Select **Certain platforms aren’t available with this product** (or any other applicable option) in the modal window and click the **Switch to Facebook Login** button.
1. Navigate to the **Facebook Login** section in the left-hand sidebar, click **Settings**.
1. For the **Valid OAuth Redirect URIs** setting, enter the value from the **Redirect URI** field in Social Feeds.
1. Click the **Save Changes** button.
1. Navigate to **App Settings** → **Basic** item in the left-hand sidebar.
1. Enter your domain name to the **App Domains** field.
1. Click the **Save Changes** button.
1. Copy the **App ID** from Facebook and paste in the **Client ID** field in Social Feeds.
1. Copy the **App Secret** from Facebook and paste in the **Client Secret** field in Social Feeds.
1. Save the Social Feeds source, ready to connect.

**Comment by jamesmacwhite** [comment] 2024-02-08 11:43
Thanks Josh, this is an excellent find. I did also come across some other developers mentioning they created a business app and then switched to Facebook login and this appeared to work. This seems to relate to the recent changes around their app creation process where it automatically filters or provides a pre-defined set of permissions based on the type of app, compared to before. Seems somewhat backwards when you do in fact need the OAuth scopes/permissions required but you can't actually get them by choosing the app you want?!

I will test the above as soon as possible and feedback to you accordingly.

Thanks ever so much for digging into this.

**Comment by akabucko** [comment] 2024-02-09 14:59
Hi Josh & James,

@engram-design Sorry for never replying here! I had support via email too and the suggestion of adding business_management scope worked back then.

After getting these notifications, I tried to add a new source and it stopped working again getting the same unhelpful screen from Facebook.

I've followed those steps above and that did work! The only thing I needed to do was comment out the `groups_access_member_info` as you stated in [this code](https://github.com/verbb/social-feeds/blob/adae4556cab6b73ea8c91a5baf234cfb622059cd/src/sources/Facebook.php#L77-L86).

Is there any way you can omit a scope using the config file @engram-design? Instead of commenting it manually out of the plugin. Or possibly update the repository to remove the `groups_access_member_info` from the getDefaultScopes function after testing?

Thanks for your help as always on this.

**Comment by engram-design** [comment] 2024-02-09 22:55
You can't remove a default scope in the config file, but that's great to know the steps above have worked. I'll look at getting a version out to address that, and update the docs.

**Comment by jamesmacwhite** [comment] 2024-02-09 23:39
Sorry for the delay on my end. The new process with converting Facebook for Business Login to Facebook Login now allows the OAuth authorisation to work.
I did get this message when linking for the first time though:

![image](https://github.com/verbb/social-feeds/assets/8067792/7bb6c0ce-c302-4afc-83e1-399f514fa96f)

While the provider is authenitcated within the plugin settings, the page dropdown is blank. Not sure if I missed anything or triggered something else!

**Comment by engram-design** [comment] 2024-02-09 23:48
That screen should be normal, I believe. It should show you a list of pages you have access to, and you should tick the pages you want shown. As for the pages not showing up, can you try with the `business_management` scope added?

**Comment by jamesmacwhite** [comment] 2024-02-09 23:56
Thanks! Can confirm appending the `business_management` OAuth scope via social-feeds.php config works! I still had to go into the provider and manually reload the page dropdown for profiles to show up, but it does indeed work now! What a dance just to get the right OAuth permissions.

**Comment by engram-design** [comment] 2024-02-10 00:05
Great to know. I _still_ haven't figured out the deal with `business_management` - but yes you'll need to refresh the pages dropdown, as it won't fetch them automatically for performance.

Thanks for your patience with this one, I'll get that sorted ASAP.

**Comment by jamesmacwhite** [comment] 2024-02-10 00:14
Fine with me to manually refresh! Just as long as the OAuth is successful and gets the page access for pulling posts!

Thanks for your debugging and solution, because Meta/Facebook really haven't made this easy. I thought getting data from Instagram was worse, this is about on the same levels of pain! This new app process seems a bit flawed if it's not going to provide the permissions needed. I can see they ask for feedback on why you are switching certain options. I wonder if they know they are breaking apps.

**Comment by engram-design** [comment] 2024-02-10 22:59
Should be fixed in [1.0.4](https://github.com/verbb/social-feeds/releases/tag/1.0.4), and refer to the updated [docs](https://verbb.io/craft-plugins/social-feeds/docs/providers/facebook)

**Closed as completed by engram-design** 2024-02-10 22:59 UTC
